"""
FILE 08 - Kafka Producer for Prosper Loan Streaming Simulation

Purpose:
    Read JSON records generated by file 06 and send them to Kafka topic
    prosper_loan_stream one by one to simulate new loan applications.
"""

import argparse
import glob
import json
import os
import time

from kafka import KafkaProducer


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input-dir",
        default="data/processed/06_ml_classification/streaming_json_sample",
        help="Folder containing streaming simulation JSON files."
    )

    parser.add_argument(
        "--topic",
        default="prosper_loan_stream",
        help="Kafka topic name."
    )

    parser.add_argument(
        "--bootstrap-server",
        default="localhost:9092",
        help="Kafka bootstrap server."
    )

    parser.add_argument(
        "--sleep",
        type=float,
        default=1.0,
        help="Sleep time between sending records."
    )

    return parser.parse_args()


def load_json_records(input_dir):
    json_files = glob.glob(os.path.join(input_dir, "*.json"))

    if not json_files:
        raise FileNotFoundError(f"No JSON files found in: {input_dir}")

    records = []

    for file_path in json_files:
        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read().strip()

            if not content:
                continue

            try:
                data = json.loads(content)

                if isinstance(data, list):
                    records.extend(data)
                elif isinstance(data, dict):
                    records.append(data)

            except json.JSONDecodeError:
                file.seek(0)
                for line in file:
                    line = line.strip()
                    if line:
                        records.append(json.loads(line))

    return records


def create_producer(bootstrap_server):
    producer = KafkaProducer(
        bootstrap_servers=bootstrap_server,
        value_serializer=lambda value: json.dumps(value).encode("utf-8")
    )

    return producer


def main():
    args = parse_args()

    print("Kafka Producer - Prosper Loan Streaming Simulation")
    print(f"Input directory: {args.input_dir}")
    print(f"Topic: {args.topic}")
    print(f"Bootstrap server: {args.bootstrap_server}")

    records = load_json_records(args.input_dir)

    print(f"Total records to send: {len(records)}")

    producer = create_producer(args.bootstrap_server)

    for index, record in enumerate(records, start=1):
        producer.send(args.topic, value=record)
        producer.flush()

        print(f"Sent record {index}/{len(records)}")
        time.sleep(args.sleep)

    producer.close()
    print("Finished sending streaming simulation data.")


if __name__ == "__main__":
    main()