"""
FILE 09 - Kafka Producer for Prosper Loan Streaming Simulation

Purpose:
    Read JSON records generated by Source 06 and send them to Kafka topic
    prosper_loan_stream one by one to simulate new loan applications.

Execution role:
    This file is the producer side of the streaming demo.
    It sends loan records into Kafka so that Source 08 Spark Structured Streaming
    can read the records and predict Good Loan / Bad Loan in near real time.

Important execution note:
    Do NOT run this file before Source 08 has started successfully.

Correct execution order:
    1. Start HDFS.
    2. Start Kafka server in a separate terminal.
    3. Run Source 08 in main.ipynb.
    4. Wait until Source 08 prints:
           STREAMING PREDICTION STARTED
    5. Open a NEW terminal at the project root and run this file:
           python src\\09_kafka_producer.py


Path configuration:
    The default input directory is:
        data/processed/06_ml_classification/streaming_json_sample

    This folder is created by Source 06 and contains JSON records used to simulate
    streaming loan applications.

Topic used:
    prosper_loan_stream

Why this file runs separately:
    Source 08 Spark Structured Streaming keeps running and waits for messages.
    Therefore, this producer must run in another terminal so both processes can
    work at the same time.
"""

import argparse
import glob
import json
import os
import sys
import time

try:
    from kafka import KafkaProducer
except ImportError as exc:
    print("=" * 88)
    print("MISSING PYTHON PACKAGE")
    print("=" * 88)
    print("The package 'kafka-python' is not installed in the current Python environment.")
    print("Open terminal at project root and run:")
    print()
    print("pip install kafka-python")
    print()
    raise exc


DEFAULT_INPUT_DIR = "data/processed/06_ml_classification/streaming_json_sample"
DEFAULT_TOPIC = "prosper_loan_stream"
DEFAULT_BOOTSTRAP_SERVER = "localhost:9092"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Kafka Producer for Prosper Loan Streaming Simulation"
    )

    parser.add_argument(
        "--input-dir",
        default=DEFAULT_INPUT_DIR,
        help="Folder containing streaming simulation JSON files generated by Source 06."
    )

    parser.add_argument(
        "--topic",
        default=DEFAULT_TOPIC,
        help="Kafka topic name."
    )

    parser.add_argument(
        "--bootstrap-server",
        default=DEFAULT_BOOTSTRAP_SERVER,
        help="Kafka bootstrap server."
    )

    parser.add_argument(
        "--sleep",
        type=float,
        default=1.0,
        help="Sleep time between sending records."
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional maximum number of records to send. Default sends all records."
    )

    return parser.parse_args()


def print_execution_guide(args):
    print("=" * 88)
    print("SOURCE 09 - KAFKA PRODUCER")
    print("=" * 88)

    print("\nThis script sends JSON loan records into Kafka.")
    print("Make sure Source 08 Spark Structured Streaming is already running.")
    print()

    print("Expected execution order:")
    print("1. Kafka server is running.")
    print("2. Source 08 is running in main.ipynb.")
    print("3. Source 08 has printed: STREAMING PREDICTION STARTED.")
    print("4. This Source 09 producer is executed in a separate terminal.")
    print()

    print("Current configuration:")
    print(f"- Input directory     : {args.input_dir}")
    print(f"- Kafka topic         : {args.topic}")
    print(f"- Bootstrap server    : {args.bootstrap_server}")
    print(f"- Sleep per record    : {args.sleep} second(s)")
    print(f"- Record limit        : {args.limit if args.limit else 'No limit'}")
    print("=" * 88)


def validate_input_dir(input_dir):
    if not os.path.exists(input_dir):
        raise FileNotFoundError(
            f"Input directory not found: {input_dir}\n"
            "Please make sure Source 06 has already created the streaming JSON sample."
        )

    json_files = glob.glob(os.path.join(input_dir, "*.json"))

    if not json_files:
        raise FileNotFoundError(
            f"No JSON files found in: {input_dir}\n"
            "Please check whether Source 06 saved the streaming JSON sample correctly."
        )

    return json_files


def load_json_records(input_dir):
    json_files = validate_input_dir(input_dir)
    records = []

    print("\nLoading JSON records...")
    print(f"JSON files found: {len(json_files)}")

    for file_path in json_files:
        print(f"- Reading: {file_path}")

        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read().strip()

            if not content:
                continue

            try:
                data = json.loads(content)

                if isinstance(data, list):
                    records.extend(data)
                elif isinstance(data, dict):
                    records.append(data)

            except json.JSONDecodeError:
                file.seek(0)

                for line in file:
                    line = line.strip()

                    if line:
                        records.append(json.loads(line))

    return records


def create_producer(bootstrap_server):
    print("\nConnecting to Kafka...")
    print(f"Bootstrap server: {bootstrap_server}")

    producer = KafkaProducer(
        bootstrap_servers=bootstrap_server,
        value_serializer=lambda value: json.dumps(value).encode("utf-8")
    )

    print("Kafka producer connected successfully.")
    return producer


def send_records(producer, topic, records, sleep_time):
    total_records = len(records)

    print("\n" + "=" * 88)
    print("START SENDING STREAMING RECORDS")
    print("=" * 88)
    print(f"Total records to send: {total_records}")
    print(f"Kafka topic: {topic}")
    print("=" * 88)

    for index, record in enumerate(records, start=1):
        producer.send(topic, value=record)
        producer.flush()

        print(f"Sent record {index}/{total_records}")
        time.sleep(sleep_time)

    print("=" * 88)
    print("FINISHED SENDING STREAMING SIMULATION DATA")
    print("=" * 88)


def main():
    args = parse_args()
    print_execution_guide(args)

    records = load_json_records(args.input_dir)

    if args.limit is not None:
        records = records[:args.limit]
        print(f"\nRecord limit applied. Records to send: {len(records)}")

    if not records:
        print("No records to send. Producer stopped.")
        sys.exit(0)

    producer = create_producer(args.bootstrap_server)

    try:
        send_records(
            producer=producer,
            topic=args.topic,
            records=records,
            sleep_time=args.sleep
        )
    finally:
        producer.close()
        print("Kafka producer closed.")


if __name__ == "__main__":
    main()